# Generated by Django 5.1.2 on 2024-10-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='livro',
            name='arquivo_pdf_epub',
            field=models.FileField(blank=True, null=True, upload_to='livros/arquivos/'),
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='livros/capas/'),
        ),
    ]
